name: Hello World Test

on:
  push: 
    branches:
      - main
  pull-request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Hello World 
        run: echo "Hello World!"
        shell: bash

  goodbye-world:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Goodbye World 
        run: echo "Good Bye World!"
        shell: bash

      
  