name: Comment on Issues

on:
    issues:
        types: [opened]

jobs:
    comment-with-action:
        runs-on: ubuntu-latest
        steps: 
            - name: "Comment on issues"
              run: echo "${{ toJson(github.event)}}" | jq
              shell: bash